/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2019-12-11 05:48:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Practice28;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jspbook.pr47.*;
import java.util.*;

public final class Practice28_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


int[][] lectureType = {
		{0,1,1,0,1},
		{1,0,0,0,2},
		{0,0,2,0,4},
		{2,3,0,3,0},
		{0,0,0,2,0},
		{0,0,0,0,0}
};
int[][] consecutive = {
		{1,2,1,1,1},
		{2,0,1,1,1},
		{0,1,1,1,4},
		{2,1,1,1,0},
		{0,1,1,2,0},
		{1,1,1,0,0},
		
};
int[][] lectureTitle = {
		{-1,4,5,-1,5},
		{3,-1,-1,-1,1},
		{-1,-1,1,-1,7},
		{0,6,-1,6,-1},
		{-1,-1,-1,2,-1},
		{-1,-1,-1,-1,-1},
		
};
String[] titleNames={
		"웹프로그래밍","운영체제","소프트웨어프로그래밍","데이터베이스개론","자료구조","네트워크","창의와감성","사회봉사"
};
String[] days = {"월","화","수","목","금","토"};

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--문헌정보학과 20170581 이효선\r\n");
      out.write("         웹브라우저 : 크롬 -->\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      jspbook.pr47.LectureBean bean = null;
      bean = (jspbook.pr47.LectureBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (bean == null){
        bean = new jspbook.pr47.LectureBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      jspbook.pr47.LectureManager manager = null;
      synchronized (session) {
        manager = (jspbook.pr47.LectureManager) _jspx_page_context.getAttribute("manager", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (manager == null){
          manager = new jspbook.pr47.LectureManager();
          _jspx_page_context.setAttribute("manager", manager, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("bean"), request);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>강의 시간표</title>\r\n");
      out.write("<style>\r\n");
      out.write("table{\r\n");
      out.write("\tborder-collapse:collapse;\r\n");
      out.write("\twidth:60%;\r\n");
      out.write("\theight:100px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("table, td, th{\r\n");
      out.write("\tborder:solid 1px;\r\n");
      out.write("\twidth:500px;\r\n");
      out.write("\theight:50px;\r\n");
      out.write("\tfont-size:13px;\r\n");
      out.write("}\r\n");
      out.write("#major {\r\n");
      out.write("\tbackground-color: #ffe082;\r\n");
      out.write("}\r\n");
      out.write("#major_select {\r\n");
      out.write("\tbackground-color: #b2ccff;\r\n");
      out.write("}\r\n");
      out.write("#refinement {\r\n");
      out.write("\tbackground-color: #bdbdbd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div align=center><h3>강의 시간표</h3>\r\n");
      out.write("<table>\r\n");

int i;
out.println("<tr><th style='font-size:20px; font-weight:bold'>2학년</th>");
for(i=0; i<days.length-1; i++)
	out.println("<th style='font-size:20px; font-weight:bold'>"+days[i]+"</th>");
out.println("</tr>");

for(i=0; i<6; i++)
{
	out.println("<tr><td style='font-size:20px; font-weight:bold'>");
	out.print(i+1 + "</td>");
	for(int j=0; j<5; j++)
	{
		switch(lectureType[i][j])
		{
		case 1:
			out.print("<td id=major");
			break;
		case 2:
			out.print("<td id=major_select");
			break;
		case 3:
			out.print("<td id=refinement");
			break;
		default:
			out.print("<td");
		}
		if(consecutive[i][j]==1)
		{
			out.println(">");
		}
		else if(consecutive[i][j] != 0)
		{
			out.println(" rowspan='" + consecutive[i][j] + "'>");
		}
		if(lectureTitle[i][j]==-1)
		{
			out.println("&nbsp;");
		}
		else
		{
			out.println(titleNames[lectureTitle[i][j]]);
		}
		out.println("</td>");
	}
	out.println("</tr>");
}
	

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
