/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2019-11-27 17:17:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Practice33;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jspbook.pr33.*;

public final class addr_005fadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      jspbook.pr33.AddrBean addr = null;
      addr = (jspbook.pr33.AddrBean) _jspx_page_context.getAttribute("addr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (addr == null){
        addr = new jspbook.pr33.AddrBean();
        _jspx_page_context.setAttribute("addr", addr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("addr"), request);
      out.write('\r');
      out.write('\n');
      jspbook.pr33.AddrManager am = null;
      synchronized (application) {
        am = (jspbook.pr33.AddrManager) _jspx_page_context.getAttribute("am", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (am == null){
          am = new jspbook.pr33.AddrManager();
          _jspx_page_context.setAttribute("am", am, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
 am.add(addr); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>addr_add</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<h1>등록내용</h1>\r\n");
      out.write("이름:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jspbook.pr33.AddrBean)_jspx_page_context.findAttribute("addr")).getUsername())));
      out.write("<br><br>\r\n");
      out.write("전화번호:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jspbook.pr33.AddrBean)_jspx_page_context.findAttribute("addr")).getTel())));
      out.write("<br><br>\r\n");
      out.write("이메일:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jspbook.pr33.AddrBean)_jspx_page_context.findAttribute("addr")).getEmail())));
      out.write("<br><br>\r\n");
      out.write("성별:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jspbook.pr33.AddrBean)_jspx_page_context.findAttribute("addr")).getSex())));
      out.write("<br><br>\r\n");
      out.write("그룹:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jspbook.pr33.AddrBean)_jspx_page_context.findAttribute("addr")).getGroup())));
      out.write("<br><br>\r\n");
      out.write("<hr>\r\n");
      out.write("<a href=\"addr_list.jsp\">전체 목록 보기</a>\r\n");
      out.write("<a href=\"addr_list_group.jsp\">그룹별 목록 보기</a>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
