/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2019-11-07 14:16:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Practice22;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.Enumeration;

public final class Practice22_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
String[] mChoices = {"hobby"};
String[] hobbyNames = {"뉴스", "맛집", "책", "영화", "여행"};
String[] telCompany = {"010", "011", "017", "070"};
String[] gNames = {"남", "여"};

ArrayList<String> getParameterNames(HttpServletRequest request)
{
	ArrayList<String> arr = new ArrayList<String>();
	Enumeration<String> e = request.getParameterNames();
	while (e.hasMoreElements())
	{
		arr.add(e.nextElement());
	}
	return arr;
}
boolean isMultipleChoice(String paramName)
{
	if (paramName == mChoices[0])
		return true;
	else
		return false;
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Practice22</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

	ArrayList<String> arr = new ArrayList<String>();
	arr = getParameterNames(request);
	
	for (int i = 0; i < arr.size(); i++)
	{
		if (isMultipleChoice(arr.get(i)) == true)
		{
			String values[] = request.getParameterValues(arr.get(i));
			out.print(arr.get(i) + ": ");
			for (int j = 0; j < values.length; j++)
			{
				out.println(values[j] + "/");
			}
			out.println("<br>");
		}
		else
		{
			String value = request.getParameter(arr.get(i));
			out.println(arr.get(i) + ": " + value + "<br>");
		}
	}
	
	out.println("<hr><h1>Processing Parameters</h1>");
	
	for (int i = 0; i < arr.size(); i++)
	{
		if (isMultipleChoice(arr.get(i)) == true)
		{
			String values[] = request.getParameterValues(arr.get(i));
			out.print(arr.get(i) + ": ");
			for (int j = 0; j < values.length; j++)
				out.println(hobbyNames[Integer.parseInt(values[i])] + "/");
			out.println("<br>");
		}
		else if (arr.get(i) == "gender")
			out.println(arr.get(i) + ": " + gNames[Integer.parseInt(request.getParameter(arr.get(i)))]);
		else if (arr.get(i) == "phone1")
			out.println(arr.get(i) + ": " + telCompany[Integer.parseInt(request.getParameter(arr.get(i)))]);
		else
		{
			String value = request.getParameter(arr.get(i));
			out.println(arr.get(i) + ": " + value + "<br>");
		}
	}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
