/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2019-12-05 14:12:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class webprintTable_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent {


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String brd;
  private java.lang.String color;

  public java.lang.String getBrd() {
    return this.brd;
  }

  public void setBrd(java.lang.String brd) {
    this.brd = brd;
    jspContext.setAttribute("brd", brd);
  }

  public java.lang.String getColor() {
    return this.color;
  }

  public void setColor(java.lang.String color) {
    this.color = color;
    jspContext.setAttribute("color", color);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getBrd() != null ) 
      _jspx_page_context.setAttribute("brd", getBrd());
    if( getColor() != null ) 
      _jspx_page_context.setAttribute("color", getColor());

    try {
      out.write('\r');
      out.write('\n');
      jspbook.pr39.LoginBean login = null;
      login = (jspbook.pr39.LoginBean) _jspx_page_context.getAttribute("login", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (login == null){
        login = new jspbook.pr39.LoginBean();
        _jspx_page_context.setAttribute("login", login, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("login"), request);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String id = login.getId();
String pw = login.getPw();
String email = login.getEmail();
String birth = login.getBirth();
int gen = login.getGender();
// 성별 구하기
String gender;
if (gen==1)
	gender="남성";
else
	gender="여성";
// 생일 구하기
String isGrown;
if (login.isGrownUp()==true)
	isGrown="성인입니다.";
else
	isGrown="성인이 아닙니다.";
	

      out.write("\r\n");
      out.write("<div align=center>\r\n");
      out.write("<h2>");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getJspBody() != null)
        getJspBody().invoke(_jspx_sout);
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,getJspContext());
      out.write("</h2>\r\n");
      out.write("<table width=300 height=300 border=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brd}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null, false));
      out.write("\" bgcolor=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null, false));
      out.write("\" style=\"text-align:center\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>이름 : </td>\r\n");
      out.write("<td width=200>");
      out.print( id );
      out.write("</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>패스워드 : </td>\r\n");
      out.write("<td width=200>");
      out.print( pw );
      out.write("</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>이메일 : </td>\r\n");
      out.write("<td width=200>");
      out.print( email );
      out.write("</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>성별 : </td>\r\n");
      out.write("<td width=200>");
      out.print( gender );
      out.write("</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>생일 : </td>\r\n");
      out.write("<td width=200>");
      out.print( birth );
      out.write("</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=2 >");
      out.print( id );
      out.write(" 씨는 ");
      out.print( gender );
      out.write(" 이고, ");
      out.print( isGrown );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
